version: 2
jobs:
  build:
    branches:
      only:
       - master
    docker:
      - image: lgatica/openssh-client
    steps:
      - add_ssh_keys:
          fingerprints:
            - "f7:0e:2b:27:d0:46:9e:ad:9b:e6:5a:b3:67:7b:de:01"
      - run:
          name: deploy
          command: ssh -oStrictHostKeyChecking=no epickiwi@epickiwi.fr "cd GraphApiJDR && git pull origin master && ./deploy.sh"
